### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by Jasdoge** [Jasdoge/Djukebox#1]
- [x] Add Bitcoin/Litecoin address checking.
- [x] Test if tips show up while a song is playing.
- [x] Make the tip popups show the correct coin.
- [x] Add address syntax verification to editor.
- [x] Add soundcloud verification to editor.
- [ ] Research if spotify can be used over soundcloud.
- [ ] Explore advertising-mode where the Djukebox can be used to display current advertisements and offers.
- [x] Consider adding a "coin in slot" sound when someone makes a tip while no song is playing.
- [x] Add way to set a cost of a song instead of any amount.
- [x] Add QR code to front page to load the song selector in phone.
- [ ] Explore potential translations.
- [ ] Research if any businesses would be interested in it.
- [x] Convert the various currencies to give an accurate representation of the value tipped.
- [x] Ability to remove songs
- [x] Disregard songs that have no address or URL set (PHP side)
- [x] Notify songs that haven't been set up properly in the editor
